# *****************************
# CONFIGURACIÓN DE BASE DE DATOS
# *****************************

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/asistencias_db?serverTimezone=UTC}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}

# *****************************
# CONFIGURACIÓN DE HIBERNATE (JPA)
# *****************************
# SpringBoot crea automaticamente las tablas en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect